server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo ?? ??? ??? ??
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true  # print sql in console
    properties:
      hibernate:
        format_sql: true  # print sql pretty
        default_batch_fetch_size: 500 # one to many performance optimization (??? ??? ?? ? ?? ???)
    open-in-view: false   # ??? ???? ?? ??? ???? ??? ??

  servlet:
    multipart:
      max-file-size: 10MB       # one file size limit
      max-request-size: 100MB   # all file size limit

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace # console log level
    template: debug   # todo 패키지 수정

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

kakao:
  client:
    id: ENC(t5yjO+wcIlB8aurDABqkIo8UpGbdrEAbxHJD5yFNBjfigv4NAyyJJzoqRn/paoXp) # 722e99b7d8f989054a0bd9152d87d6bf
    secret: ENC(rOAovf3H1Lk6m/tn6Util9TV+1Pm1oE9Yk05SPok10qo+5scY6P1BL2ZYXPzhq+q) # e75mFITZWDJlwN230Ow0AANue6z1eGCR
    redirectUrl : http://localhost:8080/oauth/kakao/callback

token:
  secret: ENC(s0sxjY3QwbJR9J37fLVvlKER/QkFDYOSsIqUIsCxq18=) # e75mFITZWDJlwN230Ow0A
  access-token-expiration-time: 900000 # 15 minutes : 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2 weeks : 1000(ms) x 60(s) x 24(h) x 14(d)

jasypt:
  password: ${PASSWORD}